name: divider_list
description: 'A List that places items of another list as a divider between each item.'
version: 0.0.2
repository: https://github.com/akmalviya03/divider_list.git

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

